# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-03 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import olib.py.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCredential',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=olib.py.utils.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                (
                    'role',
                    models.CharField(
                        choices=[('default', 'Default'), ('named', 'Named')],
                        max_length=16,
                    ),
                ),
                ('type', models.CharField(max_length=32)),
                ('encrypted_value', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['name'], name='keys_system_name_767a03_idx'),
                    models.Index(fields=['type'], name='keys_system_type_c049b2_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('name',), name='keys_systemcredential_name_uniq'),
                    models.UniqueConstraint(
                        condition=models.Q(('role', 'default')),
                        fields=('type',),
                        name='keys_systemcredential_default_per_type_uniq',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=olib.py.utils.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                (
                    'role',
                    models.CharField(
                        choices=[('default', 'Default'), ('named', 'Named')],
                        max_length=16,
                    ),
                ),
                ('type', models.CharField(max_length=32)),
                ('encrypted_value', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credentials',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(fields=['user', 'name'], name='keys_usercr_user_id_5f3a64_idx'),
                    models.Index(fields=['user', 'type'], name='keys_usercr_user_id_0c277c_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('user', 'name'),
                        name='keys_usercredential_user_name_uniq',
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(('role', 'default')),
                        fields=('user', 'type'),
                        name='keys_usercredential_default_per_type_uniq',
                    ),
                ],
            },
        ),
    ]
