# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_systemcredential_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='source',
            field=models.CharField(
                choices=[('db', 'Database'), ('disk', 'Disk')],
                default='db',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='source_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='source_rev',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='status',
            field=models.CharField(
                choices=[('active', 'Active'), ('disabled', 'Disabled')],
                default='active',
                max_length=16,
            ),
        ),
    ]
