# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-18 17:00

from django.db import migrations


def rename_gmail_credentials_to_google(apps, schema_editor) -> None:
    """Rename Gmail credential metadata without reading or rewriting ciphertext."""
    del schema_editor
    SystemCredential = apps.get_model('keys', 'SystemCredential')
    UserCredential = apps.get_model('keys', 'UserCredential')

    canonical_gmail_default = SystemCredential.objects.filter(
        type='gmail',
        is_default=True,
        name='default:gmail',
    )
    gmail_defaults = SystemCredential.objects.filter(type='gmail', is_default=True)
    google_defaults = SystemCredential.objects.filter(type='google', is_default=True)
    if gmail_defaults.exists() and google_defaults.exists():
        raise RuntimeError('cannot migrate gmail credential: a google system default already exists')
    if canonical_gmail_default.exists() and SystemCredential.objects.filter(name='default:google').exists():
        raise RuntimeError('cannot migrate default:gmail: system credential default:google already exists')

    canonical_gmail_default.update(name='default:google')
    UserCredential.objects.filter(type='gmail').update(type='google')
    SystemCredential.objects.filter(type='gmail').update(type='google')


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0004_usercredential_source_usercredential_source_path_and_more'),
    ]

    operations = [
        migrations.RunPython(
            rename_gmail_credentials_to_google,
            migrations.RunPython.noop,
        ),
    ]
