# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0005_rename_gmail_credentials_to_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='auth_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='auth_kind',
            field=models.CharField(
                choices=[('static', 'Static'), ('oauth', 'OAuth')],
                default='static',
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='encrypted_value',
            field=models.BinaryField(blank=True, default=bytes),
        ),
    ]
