# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-19 20:25

from django.db import migrations, models


def backfill_usercredential_health(apps, schema_editor) -> None:
    """Set health fields for rows written before health tracking existed.

    Existing OAuth declarations with no grant ciphertext become
    ``oauth_not_connected``; existing static declarations with an empty secret
    become ``value_empty``. Every other row keeps the new ``ready`` default.
    """
    del schema_editor
    UserCredential = apps.get_model('keys', 'UserCredential')

    UserCredential.objects.filter(auth_kind='oauth', encrypted_value=b'').update(
        health_status='needs_attention',
        health_code='oauth_not_connected',
    )
    UserCredential.objects.filter(auth_kind='static', encrypted_value=b'').update(
        health_status='needs_attention',
        health_code='value_empty',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0006_usercredential_auth_config_usercredential_auth_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='health_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='health_status',
            field=models.CharField(
                choices=[('ready', 'Ready'), ('needs_attention', 'Needs attention')],
                default='ready',
                max_length=32,
            ),
        ),
        migrations.RunPython(
            backfill_usercredential_health,
            migrations.RunPython.noop,
        ),
    ]
