# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-06-25 23:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('identifier', models.CharField(max_length=255)),
                (
                    'config_source',
                    models.CharField(default='hardcoded', max_length=255),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='agents',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'source_rev',
                    models.CharField(default='hardcoded-v0.1', max_length=255),
                ),
                ('dirty', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('spec', models.JSONField()),
                (
                    'agent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='configs',
                        to='agents.agent',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='current_config',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='agents.agentconfig',
            ),
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('schedule', 'Schedule'),
                            ('manual', 'Manual'),
                            ('agent', 'Agent'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('disabled', 'Disabled')],
                        default='active',
                        max_length=32,
                    ),
                ),
                ('spec', models.JSONField()),
                (
                    'agent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='triggers',
                        to='agents.agent',
                    ),
                ),
                (
                    'agent_config',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='triggers',
                        to='agents.agentconfig',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('user', 'identifier'), name='agents_agent_user_identifier_uniq'),
        ),
        migrations.AddConstraint(
            model_name='trigger',
            constraint=models.UniqueConstraint(fields=('agent_config', 'name'), name='agents_trigger_config_name_uniq'),
        ),
    ]
