# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_uuid7_primary_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='spec_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
