# Generated by Django 5.2.15 on 2026-07-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_agent_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="last_fired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="config_source",
            field=models.CharField(default="ui", max_length=255),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="kind",
            field=models.CharField(
                choices=[
                    ("schedule", "Schedule"),
                    ("manual", "Manual"),
                    ("agent", "Agent"),
                    ("queue", "Queue"),
                ],
                max_length=32,
            ),
        ),
    ]
