# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-05 21:20

from django.db import migrations


def sync_schedule_beat_tasks(apps, schema_editor):
    """Create PeriodicTask rows for existing schedule triggers on current configs."""
    del apps, schema_editor
    from apps.agents.services.schedule_beat import sync_all_schedule_triggers

    sync_all_schedule_triggers()


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_trigger_scheduling_fields'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.RunPython(sync_schedule_beat_tasks, migrations.RunPython.noop),
    ]
