# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_sync_schedule_beat_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='spec_yaml',
            field=models.TextField(blank=True, default=''),
        ),
    ]
