# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agent_source_path_agent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='config_source',
            field=models.CharField(choices=[('ui', 'UI'), ('disk', 'Disk')], default='ui', max_length=255),
        ),
    ]
