# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-15 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import olib.py.utils.uuid7


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agent_config_source_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='daily_spend_limit_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='monthly_spend_limit_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='SpendPolicy',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=olib.py.utils.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'daily_spend_limit_usd',
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    'monthly_spend_limit_usd',
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='spend_policy',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
