# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-08-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agent_daily_spend_limit_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='kind',
            field=models.CharField(
                choices=[
                    ('schedule', 'Schedule'),
                    ('manual', 'Manual'),
                    ('agent', 'Agent'),
                    ('queue', 'Queue'),
                    ('button', 'Button'),
                ],
                max_length=32,
            ),
        ),
    ]
