# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-06-25 23:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('queued', 'Queued'),
                            ('running', 'Running'),
                            ('waiting', 'Waiting'),
                            ('paused', 'Paused'),
                            ('done', 'Done'),
                            ('failed', 'Failed'),
                        ],
                        default='queued',
                        max_length=32,
                    ),
                ),
                (
                    'trigger_type',
                    models.CharField(
                        choices=[('trigger', 'Trigger'), ('tool_call', 'Tool call')],
                        max_length=32,
                    ),
                ),
                ('trigger_ref', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                (
                    'agent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sessions',
                        to='agents.agent',
                    ),
                ),
                (
                    'agent_config',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='sessions',
                        to='agents.agentconfig',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AgentSessionEvent',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('seq', models.PositiveIntegerField()),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('OUTPUT', 'Output'),
                            ('INPUT', 'Input'),
                            ('TOOL_CALL', 'Tool call'),
                            ('TOOL_RESULT', 'Tool result'),
                            ('FAILURE', 'Failure'),
                            ('RESTART', 'Restart'),
                        ],
                        max_length=32,
                    ),
                ),
                ('payload', models.JSONField(default=dict)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'cost_usd',
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='events',
                        to='agent_sessions.agentsession',
                    ),
                ),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['-created_at'], name='agent_sessi_created_98fea7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['agent', '-created_at'], name='agent_sessi_agent_i_95a4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsessionevent',
            index=models.Index(fields=['session', 'seq'], name='agent_sessi_session_e7aa5d_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsessionevent',
            index=models.Index(fields=['session', 'created_at'], name='agent_sessi_session_5ac1a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentsessionevent',
            constraint=models.UniqueConstraint(fields=('session', 'seq'), name='sessions_event_session_seq_uniq'),
        ),
    ]
