# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-06-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsession',
            name='agent_config',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sessions',
                to='agents.agentconfig',
            ),
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='status',
            field=models.CharField(
                choices=[
                    ('queued', 'Queued'),
                    ('running', 'Running'),
                    ('waiting', 'Waiting'),
                    ('paused', 'Paused'),
                    ('done', 'Done'),
                ],
                default='queued',
                max_length=32,
            ),
        ),
    ]
