# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0003_uuid7_primary_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
    ]
