# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-15 23:06

import django.db.models.deletion
from django.db import migrations, models

import olib.py.utils.uuid7


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0004_agentsession_name'),
        ('agents', '0010_agent_daily_spend_limit_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyUsage',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=olib.py.utils.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('hour', models.DateTimeField()),
                ('model', models.CharField(max_length=255)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('cached_input_tokens', models.PositiveBigIntegerField(default=0)),
                (
                    'cache_creation_input_tokens',
                    models.PositiveBigIntegerField(default=0),
                ),
                (
                    'cost_usd',
                    models.DecimalField(decimal_places=6, default=0, max_digits=14),
                ),
                ('iteration_count', models.PositiveIntegerField(default=0)),
                ('tool_call_count', models.PositiveIntegerField(default=0)),
                (
                    'agent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='hourly_usage',
                        to='agents.agent',
                    ),
                ),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'hour'], name='agent_sessi_agent_i_e7ef07_idx')],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('agent', 'hour', 'model'),
                        name='sessions_hourlyusage_agent_hour_model_uniq',
                    )
                ],
            },
        ),
    ]
