# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-26 19:13

import django.db.models.deletion
from django.db import migrations, models

import olib.py.utils.uuid7


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0005_hourlyusage'),
        ('agents', '0010_agent_daily_spend_limit_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSessionActivity',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=olib.py.utils.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('seq', models.PositiveIntegerField()),
                ('revision', models.PositiveIntegerField(default=1)),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('input', 'Input'),
                            ('output', 'Output'),
                            ('tool', 'Tool'),
                            ('llm', 'LLM'),
                            ('span', 'Span'),
                            ('status', 'Status'),
                            ('subagent', 'Sub-agent'),
                            ('failure', 'Failure'),
                            ('restart', 'Restart'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('running', 'Running'),
                            ('succeeded', 'Succeeded'),
                            ('failed', 'Failed'),
                            ('cancelled', 'Cancelled'),
                        ],
                        max_length=32,
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, default='', max_length=512)),
                ('details', models.JSONField(default=dict)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'cost_usd',
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.AddField(
            model_name='agentsession',
            name='parent_session',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='child_sessions',
                to='agent_sessions.agentsession',
            ),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['parent_session'], name='agent_sessi_parent__9cc333_idx'),
        ),
        migrations.AddField(
            model_name='agentsessionactivity',
            name='child_session',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='parent_activity',
                to='agent_sessions.agentsession',
            ),
        ),
        migrations.AddField(
            model_name='agentsessionactivity',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='agent_sessions.agentsessionactivity',
            ),
        ),
        migrations.AddField(
            model_name='agentsessionactivity',
            name='session',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='activities',
                to='agent_sessions.agentsession',
            ),
        ),
        migrations.AddIndex(
            model_name='agentsessionactivity',
            index=models.Index(fields=['session', 'seq'], name='agent_sessi_session_c6a1c0_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsessionactivity',
            index=models.Index(fields=['session', 'created_at'], name='agent_sessi_session_e0f717_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsessionactivity',
            index=models.Index(fields=['parent'], name='agent_sessi_parent__6b1e64_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentsessionactivity',
            constraint=models.UniqueConstraint(fields=('session', 'seq'), name='sessions_activity_session_seq_uniq'),
        ),
    ]
