# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-26 19:41

import json
from collections import defaultdict, deque
from typing import Any

from django.db import migrations

_ACTIVITY_NAME_MAX_LENGTH = 255
_ACTIVITY_SUMMARY_MAX_LENGTH = 512
_LEGACY_FAILURE_CODE = 'legacy_failure'
# Closed vocabulary emitted by the pre-migration runner errors, provider
# adapters, and worker boundary. Shape checks are insufficient because secrets
# can themselves be identifier-shaped.
_KNOWN_LEGACY_FAILURE_CODES = frozenset(
    {
        'missing_openai_credentials',
        'missing_anthropic_credentials',
        'unsupported_llm_provider',
        'credential_storage_misconfigured',
        'session_iteration_limit',
        'session_spend_limit',
        'agent_daily_spend_limit',
        'agent_monthly_spend_limit',
        'user_daily_spend_limit',
        'user_monthly_spend_limit',
        'provider_failure',
        'unexpected_failure',
    }
)


def _payload_dict(payload: object) -> dict[str, Any] | None:
    """Return a shallow payload copy when the legacy JSON value is an object."""
    if not isinstance(payload, dict):
        return None
    return dict(payload)


def _pairing_call_id(payload: object) -> str | None:
    """Return a usable legacy call ID without conflating malformed values."""
    payload_dict = _payload_dict(payload)
    if payload_dict is None:
        return None
    call_id = payload_dict.get('call_id')
    if not isinstance(call_id, str) or not call_id:
        return None
    return call_id


def _tool_call_payload_is_valid(payload: object) -> bool:
    """Require the complete legacy structure needed for an operational tool."""
    payload_dict = _payload_dict(payload)
    if payload_dict is None or _pairing_call_id(payload_dict) is None:
        return False
    instance = payload_dict.get('instance_id') or payload_dict.get('tool')
    function = payload_dict.get('function')
    if not isinstance(instance, str) or not instance.strip() or '\x00' in instance:
        return False
    if not isinstance(function, str) or not function.strip() or '\x00' in function:
        return False
    return (
        len(f'{instance}__{function}') <= _ACTIVITY_NAME_MAX_LENGTH
        and len(function) <= _ACTIVITY_SUMMARY_MAX_LENGTH
        and isinstance(payload_dict.get('arguments'), dict)
    )


def _tool_result_payload_is_valid(payload: object) -> bool:
    """Require the legacy result envelope and its string wire representation."""
    payload_dict = _payload_dict(payload)
    return (
        payload_dict is not None
        and _pairing_call_id(payload_dict) is not None
        and isinstance(payload_dict.get('content'), str)
    )


def _known_payload_is_valid(kind: str, payload: object) -> bool:
    """Validate the minimal object shape for a known non-tool legacy kind."""
    payload_dict = _payload_dict(payload)
    if payload_dict is None:
        return False
    if kind in {'INPUT', 'OUTPUT'}:
        return isinstance(payload_dict.get('content'), str)
    return kind in {'FAILURE', 'RESTART'}


def _result_is_failure(content: object) -> bool:
    """Recognize structured legacy tool results that represent failure."""
    parsed = content
    if isinstance(content, str):
        try:
            parsed = json.loads(content)
        except (json.JSONDecodeError, TypeError):
            return False
    if not isinstance(parsed, dict):
        return False
    return 'failure' in parsed or parsed.get('ok') is False


def _safe_details(payload: object) -> dict[str, Any]:
    """Preserve malformed payloads in an object suitable for activity details."""
    payload_dict = _payload_dict(payload)
    if payload_dict is not None:
        return payload_dict
    return {
        'legacy_malformed_payload': True,
        'legacy_payload': payload,
    }


def _result_details(payload: object) -> dict[str, Any]:
    """Build loss-aware details for a legacy tool-result payload."""
    payload_dict = _payload_dict(payload)
    if payload_dict is None:
        return {
            'legacy_malformed_payload': True,
            'legacy_payload': payload,
        }
    metadata = {key: value for key, value in payload_dict.items() if key not in {'call_id', 'content'}}
    return {
        'call_id': payload_dict.get('call_id'),
        'content': payload_dict.get('content'),
        'result_metadata': metadata,
    }


def _tool_name(details: dict[str, Any]) -> str:
    """Derive a stable tool activity name from available legacy metadata."""
    instance = details.get('instance_id') or details.get('tool')
    function = details.get('function')
    if instance and function:
        return f'{instance}__{function}'
    if function:
        return str(function)
    if instance:
        return str(instance)
    return 'legacy_tool'


def _common_values(event: Any) -> dict[str, Any]:
    """Copy metadata fields shared by legacy events and activities."""
    return {
        'session_id': event.session_id,
        'seq': event.seq,
        'model': event.model,
        'input_tokens': event.input_tokens,
        'output_tokens': event.output_tokens,
        'cost_usd': event.cost_usd,
        'latency_ms': event.latency_ms,
    }


def _result_field_metadata(result: Any) -> dict[str, Any]:
    """Preserve non-latency result columns that cannot all occupy the tool envelope."""
    fields = {
        'model': result.model,
        'input_tokens': result.input_tokens,
        'output_tokens': result.output_tokens,
        'cost_usd': str(result.cost_usd) if result.cost_usd is not None else None,
    }
    return {key: value for key, value in fields.items() if value is not None}


def _resequence_existing_activities(
    Activity: Any,
    activities: list[Any],
    surviving_events: list[Any],
    consumed_result_ids: set[Any],
) -> list[Any]:
    """Reserve legacy sequences and move all unrelated rows behind them stably."""
    surviving_by_id = {event.id: event for event in surviving_events}
    retained = [activity for activity in activities if activity.id not in consumed_result_ids]
    extras = [activity for activity in retained if activity.id not in surviving_by_id]
    extras.sort(key=lambda activity: (activity.seq, activity.created_at, str(activity.id)))
    next_extra_seq = max((event.seq for event in surviving_events), default=0) + 1
    final_sequences = {
        **{activity.id: surviving_by_id[activity.id].seq for activity in retained if activity.id in surviving_by_id},
        **{activity.id: next_extra_seq + index for index, activity in enumerate(extras)},
    }
    changing = [activity for activity in retained if activity.seq != final_sequences[activity.id]]
    if not changing:
        return retained

    highest_seq = max(
        [activity.seq for activity in retained] + list(final_sequences.values()),
        default=0,
    )
    for index, activity in enumerate(changing, start=1):
        activity.seq = highest_seq + index
    Activity.objects.bulk_update(changing, ['seq'])
    for activity in changing:
        activity.seq = final_sequences[activity.id]
    Activity.objects.bulk_update(changing, ['seq'])
    return retained


def _pair_tool_rows(events: list[Any]) -> tuple[dict[Any, Any], set[Any]]:
    """Pair duplicate call IDs FIFO within one session and only in forward order."""
    pending_calls: dict[str, deque[Any]] = defaultdict(deque)
    paired_results: dict[Any, Any] = {}
    consumed_result_ids: set[Any] = set()

    for event in events:
        call_id = _pairing_call_id(event.payload)
        if call_id is None:
            continue
        if event.kind == 'TOOL_CALL' and _tool_call_payload_is_valid(event.payload):
            pending_calls[call_id].append(event)
        elif event.kind == 'TOOL_RESULT' and _tool_result_payload_is_valid(event.payload) and pending_calls[call_id]:
            call = pending_calls[call_id].popleft()
            paired_results[call.id] = event
            consumed_result_ids.add(event.id)

    return paired_results, consumed_result_ids


def _tool_call_values(event: Any, result: Any | None) -> dict[str, Any]:
    """Build a unified tool activity payload from one call and optional result."""
    if not _tool_call_payload_is_valid(event.payload):
        return _malformed_advisory_values(event, name='legacy_malformed_tool_call')

    details = _safe_details(event.payload)
    values = _common_values(event)
    status = 'failed'
    if result is None:
        details['legacy_orphan'] = True
    else:
        result_payload = _payload_dict(result.payload)
        result_content = result_payload.get('content') if result_payload is not None else None
        details['result'] = result_content
        details['result_metadata'] = (
            {key: value for key, value in result_payload.items() if key not in {'call_id', 'content'}}
            if result_payload is not None
            else {'legacy_payload': result.payload, 'legacy_malformed_payload': True}
        )
        details['result_latency_ms'] = result.latency_ms
        details['legacy_result_id'] = str(result.id)
        details['legacy_result_seq'] = result.seq
        details['legacy_result_created_at'] = result.created_at.isoformat()
        legacy_result_fields = _result_field_metadata(result)
        if legacy_result_fields:
            details['legacy_result_fields'] = legacy_result_fields
        status = 'failed' if _result_is_failure(result_content) else 'succeeded'
        values['latency_ms'] = result.latency_ms if result.latency_ms is not None else event.latency_ms
        for field in ('model', 'input_tokens', 'output_tokens', 'cost_usd'):
            if values[field] is None:
                values[field] = getattr(result, field)

    values.update(
        {
            'kind': 'tool',
            'status': status,
            'name': _tool_name(details),
            'summary': str(details.get('function') or details.get('tool') or 'Legacy tool call'),
            'details': details,
        }
    )
    return values


def _orphan_result_values(event: Any) -> dict[str, Any]:
    """Build a status advisory for an unmatched or malformed tool result."""
    if not _tool_result_payload_is_valid(event.payload):
        return _malformed_advisory_values(event, name='legacy_malformed_tool_result')

    details = _result_details(event.payload)
    details['legacy_orphan_tool_result'] = True
    values = _common_values(event)
    values.update(
        {
            'kind': 'status',
            'status': 'succeeded',
            'name': 'legacy_tool_result',
            'summary': 'Orphan legacy tool result',
            'details': details,
        }
    )
    return values


def _malformed_advisory_values(event: Any, *, name: str) -> dict[str, Any]:
    """Build a non-operational status advisory retaining malformed raw data."""
    values = _common_values(event)
    values.update(
        {
            'kind': 'status',
            'status': 'succeeded',
            'name': name,
            'summary': f'Malformed legacy {event.kind} payload',
            'details': {
                'legacy_malformed_payload': True,
                'legacy_malformed_tool_call': event.kind == 'TOOL_CALL',
                'legacy_malformed_tool_result': event.kind == 'TOOL_RESULT',
                'legacy_kind': event.kind,
                'legacy_payload': event.payload,
            },
        }
    )
    return values


def _legacy_failure_code(payload: object) -> str:
    """Retain only machine codes emitted by known pre-migration code paths."""
    payload_dict = _payload_dict(payload)
    code = payload_dict.get('code') if payload_dict is not None else None
    if isinstance(code, str) and code in _KNOWN_LEGACY_FAILURE_CODES:
        return code
    return _LEGACY_FAILURE_CODE


def _failure_event_values(event: Any) -> dict[str, Any]:
    """Sanitize a historical failure, preferring security over raw diagnostics.

    Legacy failure payloads were not constrained and may contain credentials,
    request metadata, or tracebacks. Canonical activities intentionally retain
    only provenance, a generic message, and a validated machine code; losing
    historical diagnostic text prevents those values from reaching SSE.
    """
    message = 'Historical session failure'
    values = _common_values(event)
    values.update(
        {
            'kind': 'failure',
            'status': 'failed',
            'name': 'failure',
            'summary': message,
            'details': {
                'legacy_failure': True,
                'message': message,
                'code': _legacy_failure_code(event.payload),
            },
        }
    )
    return values


def _regular_event_values(event: Any) -> dict[str, Any]:
    """Map a regular event or preserve unknown and malformed data as advisory."""
    if event.kind == 'FAILURE':
        return _failure_event_values(event)

    kind_map = {
        'INPUT': ('input', 'succeeded', 'input'),
        'OUTPUT': ('output', 'succeeded', 'output'),
        'RESTART': ('restart', 'succeeded', 'restart'),
    }
    mapped = kind_map.get(event.kind)
    if mapped is None:
        mapped = ('status', 'succeeded', 'legacy_event')
        details = {
            'legacy_unknown_kind': True,
            'legacy_kind': event.kind,
            'legacy_payload': event.payload,
        }
        summary = f'Unknown legacy event kind: {event.kind}'
    elif not _known_payload_is_valid(event.kind, event.payload):
        return _malformed_advisory_values(event, name='legacy_malformed_event')
    else:
        details = _safe_details(event.payload)
        summary = ''
        if event.kind in {'INPUT', 'OUTPUT'}:
            content = details['content']
            summary = (content[:120] + '…') if len(content) > 120 else content

    kind, status, name = mapped
    values = _common_values(event)
    values.update(
        {
            'kind': kind,
            'status': status,
            'name': name,
            'summary': summary,
            'details': details,
        }
    )
    return values


def _event_values(event: Any, paired_results: dict[Any, Any]) -> dict[str, Any]:
    """Dispatch one surviving legacy event to its activity field mapping."""
    if event.kind == 'TOOL_CALL':
        return _tool_call_values(event, paired_results.get(event.id))
    if event.kind == 'TOOL_RESULT':
        return _orphan_result_values(event)
    return _regular_event_values(event)


def forwards(apps: Any, schema_editor: Any) -> None:
    """Copy legacy events into activities without removing still-active event rows."""
    Event = apps.get_model('agent_sessions', 'AgentSessionEvent')
    Activity = apps.get_model('agent_sessions', 'AgentSessionActivity')
    session_ids = Event.objects.order_by().values_list('session_id', flat=True).distinct()
    update_fields = [
        'seq',
        'kind',
        'status',
        'name',
        'summary',
        'details',
        'model',
        'input_tokens',
        'output_tokens',
        'cost_usd',
        'latency_ms',
        'created_at',
    ]

    for session_id in session_ids.iterator():
        events = list(Event.objects.filter(session_id=session_id).order_by('seq', 'id'))
        activities = list(Activity.objects.filter(session_id=session_id).order_by('seq', 'created_at', 'id'))
        paired_results, consumed_result_ids = _pair_tool_rows(events)
        surviving_events = [event for event in events if event.id not in consumed_result_ids]
        if consumed_result_ids:
            Activity.objects.filter(session_id=session_id, id__in=consumed_result_ids).delete()
        retained = _resequence_existing_activities(
            Activity,
            activities,
            surviving_events,
            consumed_result_ids,
        )
        activities_by_id = {activity.id: activity for activity in retained}
        to_update = []
        to_create = []
        for event in surviving_events:
            values = _event_values(event, paired_results)
            activity = activities_by_id.get(event.id)
            if activity is None:
                to_create.append(
                    Activity(
                        id=event.id,
                        revision=1,
                        created_at=event.created_at,
                        **values,
                    )
                )
            else:
                for field, value in values.items():
                    if field != 'session_id':
                        setattr(activity, field, value)
                activity.created_at = event.created_at
                to_update.append(activity)
        if to_update:
            Activity.objects.bulk_update(to_update, update_fields)
        if to_create:
            created_at_by_id = {event.id: event.created_at for event in surviving_events}
            Activity.objects.bulk_create(to_create)
            for activity in to_create:
                activity.created_at = created_at_by_id[activity.id]
            Activity.objects.bulk_update(to_create, ['created_at'])


def backwards(apps: Any, schema_editor: Any) -> None:
    """Refuse reversal because paired tool results cannot be reconstructed losslessly."""
    raise RuntimeError('paired tool results cannot be reconstructed losslessly')


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0006_hierarchical_session_activities'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
