# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0007_migrate_events_to_activities'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentsessionactivity',
            index=models.Index(
                fields=['kind', 'status', 'created_at'],
                name='agent_sessi_kind_3497f1_idx',
            ),
        ),
    ]
