# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-26 23:23

from django.db import migrations


def reject_reverse_drop(apps, schema_editor):
    """Refuse to recreate an empty legacy table after its rows were discarded."""
    del apps, schema_editor
    raise RuntimeError('legacy session event table drop is irreversible')


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0009_activity_terminal_transition_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentSessionEvent',
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reject_reverse_drop,
        ),
    ]
