# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-08-30 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0010_remove_agentsessionevent'),
        ('agents', '0011_alter_trigger_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hourlyusage',
            name='sessions_hourlyusage_agent_hour_model_uniq',
        ),
        migrations.AddField(
            model_name='agentsession',
            name='algorithm_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='agent_sessions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='hourlyusage',
            name='algorithm_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hourlyusage',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='hourly_usage',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='agent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sessions',
                to='agents.agent',
            ),
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='agent_config',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sessions',
                to='agents.agentconfig',
            ),
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='trigger_type',
            field=models.CharField(
                choices=[
                    ('trigger', 'Trigger'),
                    ('tool_call', 'Tool call'),
                    ('algorithm', 'Algorithm'),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='hourlyusage',
            name='agent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='hourly_usage',
                to='agents.agent',
            ),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['user', '-created_at'], name='agent_sessi_user_id_658892_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(
                fields=['user', 'algorithm_id', '-created_at'],
                name='agent_sessi_user_id_17e285_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='hourlyusage',
            index=models.Index(
                fields=['user', 'algorithm_id', 'hour'],
                name='agent_sessi_user_id_a8a556_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='agentsession',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('agent__isnull', False),
                        ('agent_config__isnull', False),
                        ('algorithm_id__isnull', True),
                    ),
                    models.Q(
                        ('agent__isnull', True),
                        ('agent_config__isnull', True),
                        ('algorithm_id__isnull', False),
                        ('parent_session__isnull', True),
                    ),
                    _connector='OR',
                ),
                name='sessions_agentsession_owner_xor',
            ),
        ),
        migrations.AddConstraint(
            model_name='hourlyusage',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('agent__isnull', False), ('algorithm_id__isnull', True)),
                    models.Q(('agent__isnull', True), ('algorithm_id__isnull', False)),
                    _connector='OR',
                ),
                name='sessions_hourlyusage_owner_xor',
            ),
        ),
        migrations.AddConstraint(
            model_name='hourlyusage',
            constraint=models.UniqueConstraint(
                condition=models.Q(('agent__isnull', False)),
                fields=('agent', 'hour', 'model'),
                name='sessions_hourlyusage_agent_hour_model_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='hourlyusage',
            constraint=models.UniqueConstraint(
                condition=models.Q(('algorithm_id__isnull', False)),
                fields=('user', 'algorithm_id', 'hour', 'model'),
                name='sessions_hourlyusage_algorithm_hour_model_uniq',
            ),
        ),
    ]
