# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-08-30 16:35

from django.db import migrations


def backfill_owner_users(apps, schema_editor):
    """Copy each legacy agent owner onto its session and usage rows."""
    del schema_editor
    AgentSession = apps.get_model('agent_sessions', 'AgentSession')
    HourlyUsage = apps.get_model('agent_sessions', 'HourlyUsage')
    for session_id, user_id in AgentSession.objects.filter(user__isnull=True).values_list(
        'pk',
        'agent__user_id',
    ):
        AgentSession.objects.filter(pk=session_id).update(user_id=user_id)
    for usage_id, user_id in HourlyUsage.objects.filter(user__isnull=True).values_list(
        'pk',
        'agent__user_id',
    ):
        HourlyUsage.objects.filter(pk=usage_id).update(user_id=user_id)


class Migration(migrations.Migration):

    dependencies = [
        (
            'agent_sessions',
            '0011_remove_hourlyusage_sessions_hourlyusage_agent_hour_model_uniq_and_more',
        ),
    ]

    operations = [
        migrations.RunPython(backfill_owner_users, migrations.RunPython.noop),
    ]
