# Licensed under the Apache License, Version 2.0 (the "License");
# Copyright 2024 Øivind Loe
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0 for details.
# ~
# Generated by Django 5.2.15 on 2026-07-04 17:23

import django.db.models.deletion
from django.db import migrations, models

import olib.py.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_sessions', '0004_agentsession_name'),
        ('agents', '0003_agentconfig_spec_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=olib.py.utils.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('queue_id', models.CharField(max_length=64)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('min_hold_seconds', models.PositiveIntegerField(default=60)),
                ('early_release_seconds', models.PositiveIntegerField(default=300)),
                ('long_hold_seconds', models.PositiveIntegerField(default=3600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'agent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='queues',
                        to='agents.agent',
                    ),
                ),
                (
                    'agent_config',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='queues',
                        to='agents.agentconfig',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=olib.py.utils.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('external_id', models.CharField(default='', max_length=255)),
                ('payload', models.JSONField(default=dict)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('available', 'Available'),
                            ('taken', 'Taken'),
                            ('done', 'Done'),
                            ('failed', 'Failed'),
                            ('exhausted', 'Exhausted'),
                        ],
                        default='available',
                        max_length=32,
                    ),
                ),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'queue',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='queues.queue',
                    ),
                ),
                (
                    'taken_by_session',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='taken_queue_items',
                        to='agent_sessions.agentsession',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='QueueItemAttempt',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=olib.py.utils.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('attempt_number', models.PositiveIntegerField()),
                (
                    'outcome',
                    models.CharField(
                        choices=[
                            ('in_progress', 'In progress'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                            ('released', 'Released'),
                            ('exhausted', 'Exhausted'),
                        ],
                        default='in_progress',
                        max_length=32,
                    ),
                ),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attempts',
                        to='queues.queueitem',
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='queue_item_attempts',
                        to='agent_sessions.agentsession',
                    ),
                ),
            ],
            options={
                'ordering': ['attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=olib.py.utils.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('source_id', models.CharField(max_length=64)),
                ('adapter_type', models.CharField(max_length=64)),
                ('config', models.JSONField(default=dict)),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('disabled', 'Disabled')],
                        default='active',
                        max_length=32,
                    ),
                ),
                (
                    'credential_ref',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'queue',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sources',
                        to='queues.queue',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='queueitem',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='items',
                to='queues.source',
            ),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['agent', 'queue_id'], name='queues_queu_agent_i_4cdd09_idx'),
        ),
        migrations.AddConstraint(
            model_name='queue',
            constraint=models.UniqueConstraint(fields=('agent', 'queue_id'), name='queues_queue_agent_queue_id_uniq'),
        ),
        migrations.AddIndex(
            model_name='queueitemattempt',
            index=models.Index(fields=['item', 'attempt_number'], name='queues_queu_item_id_49d270_idx'),
        ),
        migrations.AddIndex(
            model_name='queueitemattempt',
            index=models.Index(fields=['item', 'session'], name='queues_queu_item_id_56594f_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['queue', 'source_id'], name='queues_sour_queue_i_1c9688_idx'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(
                fields=('queue', 'source_id'), name='queues_source_queue_source_id_uniq'
            ),
        ),
        migrations.AddIndex(
            model_name='queueitem',
            index=models.Index(
                fields=['queue', 'status', 'created_at'],
                name='queues_queu_queue_i_d11448_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='queueitem',
            constraint=models.UniqueConstraint(
                condition=models.Q(('source__isnull', False)),
                fields=('source', 'external_id'),
                name='queues_queueitem_source_external_id_uniq',
            ),
        ),
    ]
